src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Institution__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseEnrolled__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course Enrolled</relationshipLabel>
        <relationshipName>Course_Enrolled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Enrolled</relationshipLabel>
        <relationshipName>Course_Enrolled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Enrolled</relationshipLabel>
        <relationshipName>Course_Enrolled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <formula>Course__r.Institution__r.Name</formula>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>Liverpool</fullName>
                </value>
                <value>
                    <fullName>Oxford</fullName>
                </value>
                <value>
                    <fullName>Cambridge</fullName>
                </value>
                <value>
                    <fullName>Manchester</fullName>
                </value>
                <value>
                    <fullName>Birmingham</fullName>
                </value>
                <value>
                    <fullName>Edinburgh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Course Enrolled</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Course Enrolled ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Enrolled</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Institution__c.object
<CustomObject>
    <label>Institution</label>
    <nameField>
        <label>Institution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseEnrolledQueryAction.cls
/*----------------------------------------------------------------------
Name:       CourseEnrolledQueryAction.cls
Purpose:    Query CourseEnrolled__c record
------------------------------History----------------------------------
Version     Author              Date                        Detail Description 
-------     --------------      -----------------           ------------------
1.0         Muhammad Abrar      10-September-2018           Initial Development 
----------------------------------------------------------------------*/
public with sharing class CourseEnrolledQueryAction{

    public class CourseEnrolledInput {
        @InvocableVariable(required=true)
        public String courseEnrolledID;
    } 

    public class CourseEnrolledOutput {
        @InvocableVariable(required=true)
        public CourseEnrolled__c courseEnrolRecord;
    }

    /*----------------------------------------------------------------------
    Purpose:    Query CourseEnrolled__c record
    Parameters: CourseEnrolledInput
    Returns:    CourseEnrolledOutput
    ------------------------------History----------------------------------
    Version     Author              Date                        Detail Description 
    -------     --------------      -----------------           ------------------
    1.0         Muhammad Abrar      10-September-2018           Initial Development
    ----------------------------------------------------------------------*/
    @InvocableMethod(label='Get Course Enrol' description='Returns course enrol record.')
    public static List<CourseEnrolledOutput> getCourses(List<CourseEnrolledInput> inputs) {
        List<CourseEnrolledOutput> lstCourseEnrolls = new List<CourseEnrolledOutput>();

        Set<String> setCourseEnrolIds = new Set<String>();
        for(CourseEnrolledInput input : inputs){
            setCourseEnrolIds.add(input.courseEnrolledID);
        }

        for(CourseEnrolled__c courseEnrol : [SELECT Id, Name, Account__c, Contact__c,
                                                Course__c, Course__r.Name, Course__r.Description__c, Course__r.Duration__c, Course__r.Frequency__c, Course__r.Institution__r.Name,
                                                StartDate__c, EndDate__c, Location__c FROM CourseEnrolled__c WHERE Name IN : setCourseEnrolIds]){
                                                    
            CourseEnrolledOutput output = new CourseEnrolledOutput();
            output.courseEnrolRecord = courseEnrol;
            lstCourseEnrolls.add(output);
        }        
        
        return lstCourseEnrolls;
    }

}