src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Institution__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseEnrolled__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course Enrolled</relationshipLabel>
        <relationshipName>Course_Enrolled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Enrolled</relationshipLabel>
        <relationshipName>Course_Enrolled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Enrolled</relationshipLabel>
        <relationshipName>Course_Enrolled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <formula>Course__r.Institution__r.Name</formula>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>Liverpool</fullName>
                </value>
                <value>
                    <fullName>Oxford</fullName>
                </value>
                <value>
                    <fullName>Cambridge</fullName>
                </value>
                <value>
                    <fullName>Manchester</fullName>
                </value>
                <value>
                    <fullName>Birmingham</fullName>
                </value>
                <value>
                    <fullName>Edinburgh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Course Enrolled</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Course Enrolled ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Enrolled</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Institution__c.object
<CustomObject>
    <label>Institution</label>
    <nameField>
        <label>Institution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseEnrolledInsertAction.cls
/*----------------------------------------------------------------------
Name:       CourseEnrolledInsertAction.cls
Purpose:    Insert CourseEnrolled__c record
------------------------------History----------------------------------
Version     Author              Date                        Detail Description 
-------     --------------      -----------------           ------------------
1.0         Muhammad Abrar      10-September-2018           Initial Development 
----------------------------------------------------------------------*/
public with sharing class CourseEnrolledInsertAction{

    public class CourseEnrolledInput {
        @InvocableVariable(required=true)
        public String contactEmailAddress;

        @InvocableVariable(required=true)
        public String selectedLocation;
        
        @InvocableVariable(required=true)
        public Course__c courseRecord;
    }   

    public class CourseEnrolledOutput {
        @InvocableVariable(required=true)
        public CourseEnrolled__c courseEnrolledRecord;
    }

    /*----------------------------------------------------------------------
    Purpose:    Insert CourseEnrolled__c record
    Parameters: CourseEnrolledInput
    Returns:    CourseEnrolledOutput
    ------------------------------History----------------------------------
    Version     Author              Date                        Detail Description 
    -------     --------------      -----------------           ------------------
    1.0         Muhammad Abrar      10-September-2018           Initial Development
    ----------------------------------------------------------------------*/
    @InvocableMethod(label='Insert Course Enrolled' description='Create Course Enrolled record.')
    public static List<CourseEnrolledOutput> insertCourseEnrolled(List<CourseEnrolledInput> inputs) {
        List<CourseEnrolledOutput> results = new List<CourseEnrolledOutput>();

        for(CourseEnrolledInput input : inputs){
            User userRecord = [SELECT Id, Name, AccountId, ContactId FROM User WHERE Id = :Userinfo.getUserId() LIMIT 1];
            
            //Account accountRecord = [SELECT Id FROM Account WHERE Name = 'FutureSkills' LIMIT 1];
            Contact contactRecord = [SELECT Id, Name, Email, AccountId, Account.Name FROM Contact WHERE Email = :input.contactEmailAddress LIMIT 1];
            
            CourseEnrolled__c courseEnrolled = new CourseEnrolled__c();
                courseEnrolled.Account__c = contactRecord.AccountId;//accountRecord.Id;
                courseEnrolled.Contact__c = contactRecord.Id;
                courseEnrolled.Course__c = input.courseRecord.Id;
                courseEnrolled.StartDate__c = System.today()+5;
                courseEnrolled.EndDate__c = System.today()+10;
                courseEnrolled.Location__c = input.selectedLocation;
            insert courseEnrolled;
            
            CourseEnrolled__c querycourseEnrolled = [SELECT Id, Name, Account__c, Contact__c, 
                                                    Course__c, Course__r.Name, Course__r.Description__c, Course__r.Duration__c, Course__r.Frequency__c, Course__r.Institution__r.Name,
                                                    StartDate__c, EndDate__c, Location__c FROM CourseEnrolled__c WHERE Id =:courseEnrolled.Id LIMIT 1];

            CourseEnrolledOutput output = new CourseEnrolledOutput();
                output.courseEnrolledRecord = querycourseEnrolled;
            results.add(output);
        }

        return results;
    }
    
}