src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Institution__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Institution__c.object
<CustomObject>
    <label>Institution</label>
    <nameField>
        <label>Institution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseQueryAction.cls
/*----------------------------------------------------------------------
Name:       CourseQueryAction.cls
Purpose:    Query Course__c record
------------------------------History----------------------------------
Version     Author              Date                        Detail Description 
-------     --------------      -----------------           ------------------
1.0         Muhammad Abrar      10-September-2018           Initial Development 
----------------------------------------------------------------------*/
public with sharing class CourseQueryAction{

    public class CourseInput {
        @InvocableVariable(required=true)
        public Institution__c institutionRecord;
    }   

    /*----------------------------------------------------------------------
    Purpose:    Query Course__c record
    Parameters: CourseInput
    Returns:    Course__c
    ------------------------------History----------------------------------
    Version     Author              Date                        Detail Description 
    -------     --------------      -----------------           ------------------
    1.0         Muhammad Abrar      10-September-2018           Initial Development
    ----------------------------------------------------------------------*/
    @InvocableMethod(label='Get Course Names' description='Returns the list of course names.')
    public static List<List<Course__c>> getCourses(List<CourseInput> inputs) {
        List<List<Course__c>> lstBulkCourses = new List<List<Course__c>>();

        Set<Id> setUniqueInstitutionIds = new Set<Id>();
        for(CourseInput input : inputs){
            setUniqueInstitutionIds.add(input.institutionRecord.Id);
        }
        
        List<Course__c> lstCourses = new List<Course__c>();
        for (Course__c course : [SELECT Id, Name, Institution__c, Institution__r.Name, Duration__c, Frequency__c, Description__c FROM Course__c WHERE Institution__c IN :setUniqueInstitutionIds Order By Name ASC]) {
            lstCourses.add(course);
        }
        
        lstBulkCourses.add(lstCourses);
        
        return lstBulkCourses;
    }
    
}